Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2019-12, with the labels that each got.

#361 Configure extra_volumes when cloud_provider is set and cloud_config is not. Fixes #301
  manifests/config/kubeadm.pp
  spec/classes/config/kubeadm_spec.rb
Labels: bugfix

#366 pdksync - "MODULES-10236 disable deploy_to_forge for the module"
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#350 Adding all IPs for etcd servers to etcd server cert
  tooling/Dockerfile
  tooling/kube_tool/create_certs.rb
Labels: bugfix

#363 Fix worker k8s 1.6
  manifests/config/kubeadm.pp
  manifests/config/worker.pp
Labels: bugfix

#338 Use correct apt release on Debian/Ubuntu
  manifests/repos.pp
Labels: bugfix

#353 Add possibility to run acceptance tests with Litmus and Vagrant
  .fixtures.yml
  .sync.yml
  .travis.yml
  Gemfile
  README.md
  provision.yaml
  spec/acceptance/kubernetes_spec.rb
  spec/acceptance/nodesets/centos-72-x64.yml
  spec/acceptance/nodesets/default.yml
  spec/acceptance/nodesets/pooler/centos7.yml
  spec/acceptance/nodesets/pooler/default.yml
  spec/acceptance/nodesets/pooler/rhel7.yml
  spec/acceptance/nodesets/pooler/ubuntu-1604.yml
  spec/acceptance/nodesets/ubuntu-1604-x64.yml
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature

#368 Add Github Actions release checks
  .github/workflows/release.yml
  provision.yaml
Labels: maintenance

#369 (maint) FM-8788 testfix for redhat and centos
  .travis.yml
  provision.yaml
  spec/spec_helper_acceptance_local.rb
Labels: maintenance
