Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2020-05, with the labels that each got.

#410 (maint) Update release workflow to use 'puppet6' agent and 'spec' test exec mode
  .github/workflows/release.yml
Labels: maintenance

#405 Add option to set the dns domain in kubernetes cluster
  manifests/config/kubeadm.pp
  manifests/init.pp
  manifests/kube_addons.pp
  templates/v1beta1/config_kubeadm.yaml.erb
  templates/v1beta2/config_kubeadm.yaml.erb
Labels: feature

#407 Remove invalid field "max" from conntrack spec
  templates/v1beta1/config_kubeadm.yaml.erb
Labels: bugfix

#411 pdksync - Use abs instead of vmpooler to provision test resources
  provision.yaml
  spec/spec_helper_acceptance.rb
Labels: maintenance

#413 Fix acceptance tests
  spec/acceptance/kubernetes_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#412 Delegated PKI and adapt to k8s 1.15.3+
  Rakefile
  lib/puppet/parser/functions/kubeadm_join_flags.rb
  manifests/cluster_roles.pp
  manifests/config/kubeadm.pp
  manifests/config/worker.pp
  manifests/init.pp
  manifests/packages.pp
  spec/classes/cluster_roles_spec.rb
  spec/classes/config/kubeadm_spec.rb
  spec/classes/packages_spec.rb
  spec/defines/kubeadm_init_spec.rb
  spec/defines/kubeadm_join_spec.rb
  templates/docker/daemon_debian.json.erb
  templates/docker/daemon_redhat.json.erb
  templates/etcd/etcd.erb
  templates/etcd/etcd.service.erb
  templates/v1alpha3/config_kubeadm.yaml.erb
  templates/v1beta1/config_kubeadm.yaml.erb
  templates/v1beta2/config_kubeadm.yaml.erb
Labels: feature
