Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2020-08, with the labels that each got.

#428 pdksync - (IAC-973) - Update travis/appveyor to run on new default branch `main`
  .travis.yml
  Gemfile
  Rakefile
  metadata.json
Labels: feature

#418 Disable swap permanently
  manifests/init.pp
  manifests/kube_addons.pp
  manifests/packages.pp
  spec/classes/packages_spec.rb
  templates/docker_apt_package_pins.erb
  templates/kubernetes_apt_package_pins.erb
Labels: feature, maintenance

#433 (IAC-1062) fix tests
  Gemfile
  spec/acceptance/kubernetes_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#434 Release prep version 5.3.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance
