Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2020-09, with the labels that each got.

#436 Updates docker yumrepo default
  README.md
  REFERENCE.md
  manifests/init.pp
  manifests/repos.pp
  spec/classes/repos_spec.rb
Labels: bugfix

#438 Resolve simple puppet-lint warnings
  examples/init.pp
  manifests/cluster_roles.pp
  manifests/config/kubeadm.pp
  manifests/init.pp
  manifests/kube_addons.pp
  manifests/kubeadm_init.pp
  manifests/kubeadm_join.pp
  manifests/packages.pp
  manifests/repos.pp
  manifests/service.pp
  plans/deploy.pp
Labels: maintenance

#443 Implement advertise address for etcd
  README.md
  manifests/config/kubeadm.pp
  manifests/init.pp
  templates/etcd/etcd.erb
  templates/etcd/etcd.service.erb
Labels: feature
