Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2021-02, with the labels that each got.

#462 Allow tmp_directory to be changed
  manifests/init.pp
  manifests/packages.pp
  spec/classes/packages_spec.rb
Labels: bugfix

#477 (IAC-995) - Removal of Inappropriate Terminology
  README.md
  REFERENCE.md
  manifests/init.pp
  spec/defines/kubeadm_init_spec.rb
  spec/spec_helper_acceptance_local.rb
  tasks/swagger_k8s_get_api_versions.json
Labels: maintenance

#480 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .rubocop.yml
  .sync.yml
  .travis.yml
  metadata.json
Labels: backwards-incompatible

#484 Fix template
  templates/etcd/etcd.service.erb
Labels: bugfix

#475 Update criSocket to avoid deprecation warnings
  templates/v1alpha3/config_kubeadm.yaml.erb
  templates/v1alpha3/config_worker.yaml.erb
  templates/v1beta1/config_kubeadm.yaml.erb
  templates/v1beta1/config_worker.yaml.erb
  templates/v1beta2/config_kubeadm.yaml.erb
  templates/v1beta2/config_worker.yaml.erb
Labels: bugfix

#486 (maint) Update major dependencies prior to release
  metadata.json
Labels: maintenance

#483 Bump containerd version to 1.5.0 and fix source link
  README.md
  manifests/init.pp
  spec/classes/packages_spec.rb
Labels: bugfix
