Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2021-01, with the labels that each got.

#465 Update to puppet-module-gems 1.0, pdk-templates and new rubocop
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .rubocop.yml
  .sync.yml
  Gemfile
  Rakefile
  lib/puppet/parser/functions/kubeadm_init_flags.rb
  lib/puppet/parser/functions/kubeadm_join_flags.rb
  metadata.json
  spec/classes/config/kubeadm_spec.rb
  spec/classes/config/worker_spec.rb
Labels: maintenance

#464 add etc max-request-bytes option
  REFERENCE.md
  manifests/config/kubeadm.pp
  manifests/init.pp
  templates/etcd/etcd.erb
  templates/etcd/etcd.service.erb
Labels: feature

#472 Update link for load-balancer in README.md
  README.md
Labels: maintenance

#471 Ensure that changes to etcd systemd reload and restart etcd
  manifests/service.pp
  spec/classes/service_spec.rb
Labels: bugfix

#478 pdksync - Update gha templates
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .rubocop.yml
  Rakefile
  metadata.json
Labels: maintenance
