Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2022-10, with the labels that each got.

#580 pdksync - (PDKSync) Removal of puppet_module_gems
  .devcontainer/README.md
  Gemfile
  metadata.json
Labels: maintenance, hacktoberfest

#582 (CONT-217) Correct Kubernetes etcd_data_dir spec tests
  manifests/config/kubeadm.pp
  manifests/kubeadm_init.pp
  manifests/kubeadm_join.pp
  manifests/service.pp
  spec/classes/config/kubeadm_spec.rb
Labels: bugfix, hacktoberfest

#577 Add RedHat family as supported OS (#563)
  metadata.json
  spec/classes/init_spec.rb
Labels: community

#576 Switch containerd grpc socket to URI
  templates/containerd/config.toml.erb
Labels: community
