Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2022-12, with the labels that each got.

#597 Support overriding containerd socket path (#596)
  README.md
  manifests/init.pp
  manifests/packages.pp
  spec/classes/packages_spec.rb
  templates/containerd/config.toml.erb
Labels: community

#598 Fix executing CNI addons commands (fixes #594)
  manifests/kube_addons.pp
  spec/classes/kube_addons_spec.rb
Labels: community

#600 Stronger type checking for $node_name
  manifests/cluster_roles.pp
  manifests/config/kubeadm.pp
  manifests/config/worker.pp
  manifests/init.pp
  manifests/kube_addons.pp
  manifests/kubeadm_init.pp
  manifests/kubeadm_join.pp
  metadata.json
  spec/classes/init_spec.rb
Labels: community, bug

#599 (MAINT) Revert hardening changes
  manifests/kube_addons.pp
  manifests/kubeadm_init.pp
  manifests/kubeadm_join.pp
  manifests/packages.pp
  manifests/service.pp
  manifests/wait_for_default_sa.pp
  spec/classes/kube_addons_spec.rb
  spec/defines/kubeadm_init_spec.rb
  spec/defines/kubeadm_join_spec.rb
  spec/defines/wait_for_default_sa_spec.rb
Labels: bug

#603 pdksync - (MAINT) Remove stalebot
  .github/workflows/stale.yml
Labels: maintenance

#602 Validate namespace parameter as DNS subdomain name
  manifests/wait_for_default_sa.pp
  spec/defines/wait_for_default_sa_spec.rb
  types/namespace.pp
Labels: backwards-incompatible, community

#593 Rewrite command line arguments parsing
  tooling/Dockerfile
  tooling/kube_tool.rb
  tooling/kube_tool/clean_up.rb
  tooling/kube_tool/create_certs.rb
  tooling/kube_tool/other_params.rb
  tooling/start-kubetool.sh
Labels: community

#606 (maint) - Bump dependencies before major release
  metadata.json
Labels: maintenance

#607 (MAINT) - update-deprecated-dependency
  metadata.json
Labels: maintenance

#605 Reproducible kube-tool build
  tooling/Dockerfile
  tooling/Makefile
Labels: community, enhancement
