Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2023-01, with the labels that each got.

#609 pdksync - (CONT-494) Pin github_changelog_generator and JSON gem versions
  .sync.yml
  Gemfile
  metadata.json
Labels: maintenance

#586 add new parameter node_extra_taints
  README.md
  manifests/config/worker.pp
  manifests/init.pp
  spec/classes/config/worker_spec.rb
  templates/v1alpha3/config_worker.yaml.erb
  templates/v1beta1/config_worker.yaml.erb
  templates/v1beta2/config_worker.yaml.erb
  templates/v1beta3/config_worker.yaml.erb
Labels: feature, community

#610 Update GPG fingerprint for apt.kubernetes.io
  manifests/repos.pp
Labels: maintenance, community

#611 (MAINT) - update pdk release image
  .github/workflows/auto_release.yml
Labels: maintenance
