Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2023-06, with the labels that each got.

#631 Make cgroup_driver default to systemd
  REFERENCE.md
  manifests/config/kubeadm.pp
  manifests/config/worker.pp
  manifests/init.pp
  manifests/packages.pp
  spec/acceptance/kubernetes_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: backwards-incompatible, community

#637 (CONT-585) allow deferred function for auth password
  REFERENCE.md
  manifests/init.pp
  manifests/packages.pp
  spec/classes/packages_spec.rb
  templates/containerd/config.toml.epp
Labels: feature

#636 Update CODEOWNERS
  CODEOWNERS
Labels: maintenance

#615 Fix flannel install condition
  README.md
  manifests/kube_addons.pp
  spec/classes/kube_addons_spec.rb
  tooling/kube_tool/other_params.rb
Labels: bugfix, community

#640 pdksync - (CONT-990) - Adding Community Pull Requests template
  .github/pull_request_template.md
Labels: maintenance
