Repository puppetlabs/puppetlabs-kubernetes, pull requests merged in 2023-05, with the labels that each got.

#627 (CONT-914) - Address CI Failures
  metadata.json
  spec/acceptance/integration_kubernetes_spec.rb
  spec/acceptance/kubernetes_spec.rb
  spec/spec_helper_acceptance_local.rb
  tooling/kube_tool/create_certs.rb
  tooling/kube_tool/other_params.rb
Labels: maintenance

#629 pdksync - (CONT-930) - Roll out new changelog generator
  .github/workflows/auto_release.yml
  .github/workflows/release_prep.yml
Labels: maintenance

#630 (CONT-903) Use checkout@v3 in Kubernetes
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: maintenance

#616 (CONT-358) Syntax update
  .puppet-lint.rc
  .sync.yml
  Rakefile
  manifests/cluster_roles.pp
  manifests/config/kubeadm.pp
  manifests/config/worker.pp
  manifests/init.pp
  manifests/kube_addons.pp
  manifests/kubeadm_init.pp
  manifests/kubeadm_join.pp
  manifests/packages.pp
  manifests/repos.pp
  manifests/service.pp
  manifests/wait_for_default_sa.pp
  plans/provision_cluster.pp
Labels: bugfix

#625 General fixes
  README.md
  REFERENCE.md
  manifests/init.pp
  templates/0-containerd.conf.erb
  templates/v1beta3/config_kubeadm.yaml.erb
  tooling/kube_tool/other_params.rb
Labels: bugfix, community
